### ISSUE TITLE
Ensure all contributors are listed in the authors file

### ISSUE THREAD

**Issue by ergo** [AppEnlight/appenlight-client-js#15]
Hi guys, I'm cleaning things and adding some missing stuff into the repo (and others), like... full bsd license text ;)
I'm listing you here to ensure we have every author of all contributions signing the authors file.
Please add date to your names, thanks!

@idpaterson 

@jlvcm

**Comment by idpaterson** [comment]
#16, date should correspond to the first contribution, correct?

**Comment by ergo** [comment]
Ideally yes, thanks!
