### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'a.stack.length')

### ISSUE THREAD

**Issue by luk156** [AppEnlight/appenlight-client-js#4]
https://appenlight.com/#/report/16314403/33478336

**Comment by ergo** [comment]
Hi, can you write something more about this report?
I've made it private again - you don't have to make it public to share with me.

**Comment by ergo** [comment]
Ok, I see where is the problem, need to determine a proper fix.
Thanks

**Comment by ergo** [comment]
@luk156 Can you confirm this is fixed for you in latest version from the client released in august?

**Comment by luk156** [comment]
no, https://appenlight.com/#/report/16755004/35341857

but https://github.com/AppEnlight/appenlight-client-js/blob/master/appenlight-client.js report version 0.2
