### ISSUE TITLE
Tags and extra on logs

### ISSUE THREAD

**Issue by idpaterson** [AppEnlight/appenlight-client-js#9]
I noticed that global tags and extra information are not applied in `log`, only `handleError`. I am not very familiar with the Python version but I believe that `extra` (a generic property named by the `logging` module) can be provided at the log level. There are a few reasons I did not create a pull request to address this yet:

1. I am not sure whether there is a difference between tags and extra or if it is just the same concept in two different contexts.
2. I am not sure whether the global tags and extra already set for errors should also automatically apply to logs.
3. The log method already takes quite a few arguments; `uuid` is unused but to guarantee backwards compatibility an `extra` (or more appropriately named for JS) param would need to be added at the end of the argument list... but that makes for quite garish logging even with the new convenience methods `AppEnlight.debug('Some message', undefined, null, { the: 'data' })`. I feel like the argument list should be `(level, message, extra, namespace, uuid)` deprioritizing the `namespace` override and whatever `uuid` is, or more appropriately `(level, message, options)` where all overrides can be specified in an options map without dancing around argument order when something new is added. That could be type-checked to support the old behavior where the third argument is a namespace string.

Thanks @ergo, if you have some ideas to share I can do a PR tomorrow (currently evening here). I am integrating appenlight-client into a Chrome browser extension that is used by our research staff and my colleague has been working on [a](https://github.com/Newstex/appenlight-reporter) [few](https://github.com/Newstex/winston-appenlight) [new](https://github.com/Newstex/express-appenlight) [integrations](https://github.com/Newstex/appenlight-lambda) for Node.

**Comment by ergo** [comment]
Hey @idpaterson,

Logs do not have `extra` property at all, historically reports had some fields like `message` for custom developer information storage, and over time I rolled everything into `extra` dictionary that is supposed to hold this extra info - but it doesn't do much more for now, and it is not same thing as `extra=` from python logging module .

For python logs `extra` allows developer to pass arbitrary information in logs themselves - this is what python client uses to build "tags" for app enlight - it has nothing to do with the `extra` property for the reports API.

So for the logs - extra keyword doesn't really make much sense - just use tags directly to tag the requests.

`uuid` IS used to give logs some more context - so if you have a request with uuid you can do 2 handy things:

1. Show logs belonging to this single request.
2. If you have an exception report you can also show logs that belong to this single request which is quite handy for things like failing API's etc.

I hope this clears up things a bit?

**Comment by idpaterson** [comment]
Thanks for the clarification, so it sounds like my pull request should:

1. Pass the currently unused `uuid` parameter in to the log buffer (it sounds like it should map to `request_id`)
2. Add an argument to the log method for applying tags 
3. Add the global tags to log messages

**Comment by ergo** [comment]
Yes, all of that seems reasonable.
